### ISSUE TITLE
XO standard

### ISSUE THREAD

**Issue by Qix-** [dthree/wat#10]
I noticed the readme wanted to be XO compliant. I [went ahead and started](/Qix-/wat/tree/xo) but it looks like it's going to be a hefty job.

If someone would like to jump in and help complete it, that'd be great :) I can't devote much more time to it, though I got rid of most of the errors and configuration.

---

Gulpfile.js is either going to need to be ES2015 compliant or XO is going to need a way to look at comments to negate the `esnext` configuration value.

// @sindresorhus

**Comment by dthree** [comment]
@Qix- can you PR what you have? I can wrap it up, but linting affects so many files and I'm doing large refactors, so I don't want it to get too deviated.

Yeah - this is my first Babel run, so I don't know the standard on that kind of thing. I don't want the Gulpfile to be ES2015 compliant as then no one can rebuild docs unless they're running IOJS, which is stupid. Can you just not XO the gulpfile?

**Comment by Qix-** [comment]
You can actually run the Gulpfile using babel if you include babel-core. It's a feature of Gulp. Just rename it to `Gulpfile.babel.js` and dev-depend on `babel-core`.

**Comment by dthree** [comment]
Oh that's good. Then let's just do that. I'll through that together after I get your PR.

**Comment by dthree** [comment]
@Qix- Not related, but would you mind checking out these guidelines and giving advice? I need to make editing easy, but uniform so I need to find a happy medium.

https://github.com/dthree/wat/blob/master/editing.md

Thanks!

**Comment by Qix-** [comment]
@dthree looks good to me :) Ill get the PR together sometime soon.

**Comment by dthree** [comment]
Ok thanks!

Btw, if you're up to it and think you'll have time to do so, I wouldn't mind giving you rights to this repo: I'm probably going to need help with PRs when I publish it, it all goes good :)

**Comment by Qix-** [comment]
Sure, I could do that :)

**Comment by dthree** [comment]
Sweet :)

I'm probably going to be doing a ton of preps before 1.0 though: The thing with lib is that it's going to go in one of exactly two directions:

1. It's taken seriously and gets adopted, and it'll be all over the place.
2. It's not, so will be irrelevant, and contributions won't be worth the effort for the community. 

If it's really taken seriously, people will want to put these badges on their repos as they know people will use this, and it'll be a bonus for them: their library is that much more accessible.

[![Wat: Cheat Sheeted](https://img.shields.io/badge/wat-cheat%20sheeted-blue.svg)](https://github.com/dthree/wat)

So I guess I just need:

1. Perfect functionality,
2. A ton of starting docs
3. Release it with bang - get it out everywhere all at once so people start building on it immediately. If it starts with that momentum, we can ride it and use that to get more people to adopt it, etc. etc.

**Comment by dthree** [comment]
@Qix- felt bad as I did a huge refactor which probably messed up a bunch of your linting work, so I finished all the XO linting today. We are 100% good :grinning:
