### ISSUE TITLE
Proxy Issues?

### ISSUE THREAD

**Issue by tooolbox** [dthree/wat#11]
When I attempt to pull up certain commands in `Wat`, such as `vantage auth` or `vantage firewall reject`, I get this:

```
Unexpected Error:  { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
````

My internet is going via an HTTP proxy set in the OSX system settings, and I'm guessing that this may be the issue.  Any thoughts?  (If it's just a lack of implementation, and you point me to the code in question, I may be able to try some stuff out.)

**Comment by dthree** [comment]
Right on. I have to do some research on using system proxy settings. Should probably be pretty simple. It's on the 1.0 list.

**Comment by dthree** [comment]
I allowed for setting a custom proxy in Wat. There's two supported commands now:

```
proxy add
proxy remove
```

**Comment by tooolbox** [comment]
Great!  Thanks :)
