### ISSUE TITLE
"Language?", or some sort of clarity engine

### ISSUE THREAD

**Issue by Qix-** [dthree/wat#12]
I could see this having a huge impact on other languages, such as C (for instance). Yes, man pages help, but are sometimes much more than what you need (i.e. the common example you use of argument order, etc.).

---

If I do `wat printf`, I'm going to get a few different results for a few different languages. Likewise, if I do `wat println`, I might get a few different options for clarification.

What would be cool to see in Wat is an engine for determining what result the user is *most likely* looking for, and filling in any missing pieces through continued prompt(s).

For instance, when I do type `printf` and there are are a few languages - `c` and `php`, namely - wat would ask `Language?`, in which I could respond `c`.

Further, for the REPL version, it might even be useful to specify what language(s) you're looking for. If I'm a C/JS developer, I will literally never be looking for PHP information. `lang c, js` or some similar command would be a hint to the clarity engine that I'm going to be looking for language results in either `c` or `js` (javascript).

*This* would be an incredible tool in my arsenal.

**Comment by dthree** [comment]
Great idea!

This should be pretty straightforward: Wat already tracks your command history, and, for example, if you've recently asked for 3 or more commands from a particular language or lib, it'll download all the markdown locally for that language in the background so there's no latency in future commands.

How about this:

When a user types in invalid command, I parse the index, find all partial matches, scoring them based on two-word matches, etc. etc.

I then weight the scoring by a priority scoring on the languages you use most. Any language you've never searched for gets a negative scoring. Then it'll do something like:

```
? printf

Did you mean:

  1. c printf
  2. ...
  3. ...
```

Maybe languages that have never been queried get omitted entirely.

Then the user can type:

`? 1`

And then it will pull up the first option: `c printf`.

I can also highlight the string matches in yellow background-highlighter or something.

**Comment by Qix-** [comment]
I wouldn't omit entirely. I probably haven't ever looked up Ruby stuff, though if I wanted to learn one day not seeing anything in Wat about Ruby would be discouraging. Score negatively, but include if there are empty spots.

Also, as far as the `1, 2, 3` menu pattern goes, I would discourage it for languages in particular. My reflexes are going to be quicker than to look at a menu when I see `Language` - my brain is going to realize it's asking for a language disambiguation and type in the language I'm looking for before my eyes even see the menu. :)

**Comment by dthree** [comment]
Ok no probs.

Almost done with this feature.

BTW, try this:

`npm install -g wat`
`wat stackoverflow array concat`

:fire:

**Comment by Qix-** [comment]
<img width="380" alt="screen shot 2015-08-28 at 12 47 09 am" src="https://cloud.githubusercontent.com/assets/885648/9540633/56f58522-4d1e-11e5-8a4b-46d133ff2ee0.png">

**Comment by dthree** [comment]
Did you re-install?

**Comment by dthree** [comment]
Ok try to install again.

**Comment by dthree** [comment]
@Qix- Did that `so` command ever work for you? If you run another install now, I've got a ton of updates.

**Comment by Qix-** [comment]
@dthree 
<img width="515" alt="screen shot 2015-08-28 at 10 53 06 pm" src="https://cloud.githubusercontent.com/assets/885648/9560557/97293ec2-4dd7-11e5-9c5f-49ac6b94f2d4.png">

**Comment by dthree** [comment]
ahhhh 1 sec

**Comment by dthree** [comment]
Ok fixed.

**Comment by dthree** [comment]
This is handled now. To see how it works now, do;

```bash
$ npm install -g wat
$ wat tour
```
