### ISSUE TITLE
DOS→UNIX line endings?

### ISSUE THREAD

**Issue by anko** [dthree/wat#16]
Files seem to have CRLF (DOS-style) line-endings over here. Source code more commonly has LF (UNIX-style) line-endings. ([More details on Wikipedia](https://en.wikipedia.org/wiki/Newline).)

Is there a particular reason for the DOS style? Most editors auto-detect, but I suspect this might be the reason behind e.g. wooorm/mdast#43. I haven't investigated that much though!

**Comment by dthree** [comment]
Thanks. On Windows with Sublime Text 2.

I had done this on most files but it looks like a few were missed. Before I put out a release, the project's linting will be fully caught up, which catches this.

**Comment by Qix-** [comment]
https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#coreautocrlf-og7TJ

Then use `dos2unix` (there is even an [NPM package](https://www.npmjs.com/package/dos2unix) that does the same thing) to convert your sources and whatnot, and then re-commit.

**Comment by dthree** [comment]
@Qix- very helpful, thanks! Set that up in Git.

The `dos2unix` thing would make a great Gulp plugin, btw.

**Comment by dthree** [comment]
This is fixed now.

**Comment by wooorm** [comment]
:+1:
