### ISSUE TITLE
Wat crashes by creating long tmp path / max call stack exceeded

### ISSUE THREAD

**Issue by forivall** [dthree/wat#18]
https://gist.github.com/forivall/e4cf575d0fc8a593f82c

After typing `wat tour`, I wait for a couple seconds, then the "Maximum call stack size exceeded" error occurs.

linux, iojs 3.2, npm@3. More detail is in the gist terminal log.

**Comment by dthree** [comment]
Thanks. Mid a lot of changes on `wat` at the moment, it's definitely not production ready. I did fix this particular bug, but haven't re-published as things are still broken.

If you check back in about a week, I should have something for you to try!
