### ISSUE TITLE
wat tries to create folders in /usr/lib

### ISSUE THREAD

**Issue by keis** [dthree/wat#2]
I tried installing wat using npm but when I try to start in fails with access denied trying to mkdir `/usr/lib/node_modules/wat/.local` as part of `clerk.scaffold`

the paths look vaguely xdgish so maybe $XDG_DATA_HOME is what you want

**Comment by dthree** [comment]
Okay can do - was going back and forth on where to put all the local files. Need a good cross-platform solution.

**Comment by dthree** [comment]
@keis Alright - ported everything over to `${os.tmpDir()}/.wat/.local/`, and tried this out on Windows and Ubuntu. Looks pretty good.
