### ISSUE TITLE
"err wrong command" on correct command

### ISSUE THREAD

**Issue by Qix-** [dthree/wat#21]
<img width="517" alt="screen shot 2015-10-06 at 02 16 33" src="https://cloud.githubusercontent.com/assets/885648/10303337/50589aa8-6bd0-11e5-9935-7400b5917f7b.png">

So this happened. Got `Err... wrong command` when the comment was corrected.

**Comment by dthree** [comment]
LOL you typed `js arrya slice` (spot the type?). 

Wat was smart enough to auto-correct it, but my Tour code wasn't:

```js
  tour.step(1)
    .begin(start1)
    .expect("command", function (data, cb) {
      cb(data.command === 'js array slice');
    })
    .reject('Err.. wrong command.')
    .wait(1000)
    .end(end1)
```

Fixed it to be more lenient.

**Comment by dthree** [comment]
Published the fix :)
