### ISSUE TITLE
wat should support a --version flag

### ISSUE THREAD

**Issue by iankronquist** [dthree/wat#24]
I was writing a bug report and wanted to include the version of wat I had installed.
This is what happened:
```
 $ wat --version

  Sorry, there's no command like that.

Goodbye!

```

**Comment by dthree** [comment]
Haha - good point :)

I'm also thinking of doing a notification when a new version comes out. Do you think that would be a good idea?

**Comment by iankronquist** [comment]
That sounds like a great idea!

**Comment by dthree** [comment]
Okay it's in the plan :)

**Comment by dthree** [comment]
This is now supported.
