### ISSUE TITLE
Can't use tab completion for selcting themes

### ISSUE THREAD

**Issue by passcod** [dthree/wat#26]
I expected to be able to type `theme de<TAB>` to select the default theme but nothing happened.

**Comment by dthree** [comment]
Yeah, still have to do this. Definitely on the list for 1.0!

**Comment by passcod** [comment]
Also forgetting that the `theme` command is for selecting, while `themes` is for listing is confusing. Spent a couple of tries wondering why `theme default` didn't work.

**Comment by dthree** [comment]
Hmm. `theme default` should set the theme to default.

Could you give me an example of what behavior you would expect?

**Comment by passcod** [comment]
Oh, oops. `theme default` certainly sets the theme, `themes default` doesn't. What I was reporting is that having just used `themes` to see what was available, I expected that `<UP ARROW> default` would set the theme, or at least give me an indication of what I'm doing wrong, instead of leaving me to wonder why the "set a theme" command isn't working.

Perhaps merging `theme` and `themes` (and maybe aliasing them to each other) would work. Or having a **Use `theme <name>` to select one** line under the `themes` list.

**Comment by dthree** [comment]
I'll just make it `theme`, and put the current one on the top of the list.

**Comment by dthree** [comment]
Should be good now.
