### ISSUE TITLE
Exiting could be more intuitive

### ISSUE THREAD

**Issue by passcod** [dthree/wat#27]
Not sure if that's a Vorpal UX issue instead.

To exit from wat:
- Ctrl-C works
- `exit` works
- Ctrl-D on an empty line does nothing (I expected exit as in shell-like behaviour)
- `q` or `quit` do nothing (I tried `q` as a reflection / habit from vim/less etc)

**Comment by dthree** [comment]
I can make `quit` an alias in vorpal - as it's pretty all-around. `q` will be added as an alias on wat.

I'll check out `Ctrl-D`. I think I remember some complication with it in Vorpal, but I'll check.

**Comment by dawsonbotsford** [comment]
Agreed entirely based upon my first experience. Under the welcome message which prints on the first load of ```wat tour``` it would be nice to also see "Exit using _ at any point in time"

**Comment by dthree** [comment]
@passcod added `quit` to Vorpal by default. `Ctrl+D` doesn't seem to have a stable handler in Node across all platforms (https://nodejs.org/api/process.html#process_signal_events), so I'm not going to do anything with it right now.

@dawsonbotsford added this message to the tour.
