### ISSUE TITLE
Node Download links

### ISSUE THREAD

**Issue by fntlnz** [dthree/wat#28]
Node download links refers to node 0.12.7 under the [faqs](https://github.com/dthree/wat#sorry-i-dont-speak-node).

I think that these should be updated to 4.2.0.

What do you think?

**Comment by dthree** [comment]
Good point. Feel free to do a PR, otherwise I'll get to it in a little.

**Comment by dthree** [comment]
Actually, Node `v4.x` currently has keypress bugs on certain Windows platforms, and this is mid being debugged.

https://github.com/nodejs/node/issues/2996

As soon as this is fixed, I'll change the link.
