### ISSUE TITLE
Failed to install on Windows

### ISSUE THREAD

**Issue by Toltar** [dthree/wat#3]
Hello you have an intresting project that would be awesome for me to contribute. Though I am having trouble installing it or installing it correctly as seen here:  
```
26980 verbose stack Error: ENOENT, open 'C:\Program Files\nodejs\?.cmd'
26980 verbose stack     at Error (native)
26981 verbose cwd C:\WINDOWS\system32
26982 error Windows_NT 6.3.9600
26983 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program           Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "wat"
26984 error node v0.12.7
26985 error npm  v3.2.2
26986 error path C:\Program Files\nodejs\?.cmd
26987 error code ENOENT
26988 error errno -4058
26989 error enoent ENOENT, open 'C:\Program Files\nodejs\?.cmd'
26989 error enoent This is most likely not a problem with npm itself
26989 error enoent and is related to npm not being able to find a file.
26990 verbose exit [ -4058, true ]
```
Any ideas of why I am receiving these errors? Would it be more appropriate to put this issue on npm?

**Comment by Qix-** [comment]
This doesn't look like a `wat` problem. Try re-installing NPM.

**Comment by dthree** [comment]
Yeah, I'd have to agree with @Qix- haven't seen that before. Let me know if you still have trouble after reinstalling NPM and maybe node.

**Comment by vweevers** [comment]
No, it's `wat`. Happens because you [cant use a question mark in Windows filenames](https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words). So this binary name is the problem:

```js
"bin": {
    "?": "./bin/index.js",
    "wat": "./bin/index.js"
  }
```

**Comment by dthree** [comment]
aha! good catch

**Comment by Toltar** [comment]
Oh ok so basically just that the file name in the binary somehow needs to be fixed.

**Comment by dthree** [comment]
that's just my package.json I thought i'd be fancy and make '?' a binary command. I felt like I was cheating somehow, and I was right!

**Comment by vweevers** [comment]
You could instead advise *nix users who want the "?" name to create an alias.

**Comment by Qix-** [comment]
Aha, yes definitely cheating. That's going to be pretty standard across systems.

Alternatively, suggest making an alias on *nix systems:

```shell
alias ?=wut
```

:kimono:

**Comment by dthree** [comment]
Okay this is fixed - Windows build show work now. @Toltar  @vweevers if you want to try it out.
