### ISSUE TITLE
verb templates

### ISSUE THREAD

**Issue by tomByrer** [dthree/wat#30]
More of an introduction & self-note to use [verb](https://github.com/verbose/verb)'s doc templating system as a way to semi-automatically make wat docs.

**Comment by dthree** [comment]
Nice - looks cool. 

If have to look at it a bit more, but I can't tell if verb specializes in generating docs, or parsing existing docs. All `wat` is trying to do is parse existing documentation on the fly. I've got markdown pretty well taped, but I'm looking for someone / something to parse other types of docs, priority being a `godoc` document generator.

Wat also expects an exact format to parse the docs into - you can look at the `docs/js` section to see what it's sort of expecting.

**Comment by tomByrer** [comment]
It is just a templating system, helpful to save typing.  [example template](https://github.com/jonschlinkert/micromatch/blob/master/.verb.md).
Written by the same guy who helped out with [Assemble](http://assemble.io/) static site generator.

**Comment by tomByrer** [comment]
My main driver is a hope to have 1 source document system that is multi-target: README.md, HTML docs, wat, & [devdocs.io/](https://github.com/Thibaut/devdocs).

**Comment by dthree** [comment]
Ah - that would be great to have!

I don't think this is for Wat - but have no worries - the goal with Wat is to have it be compatible with all other things naturally, so everything is automatically Wat compatible.

So far, any docs with API in a readme is wat compatible. Next, I want to make an HTML parser, and that will open up a whole other set of docs. After that, a GoDoc parser.

**Comment by dthree** [comment]
Gonna close this for now, but feel free to discuss ideas with me on this :)
