### ISSUE TITLE
CLI REPL requires two ^C to exit

### ISSUE THREAD

**Issue by Qix-** [dthree/wat#5]
Hitting CTRL+C once puts wat into a weird, hung state and requires a second CTRL+C to actually exit.

**Comment by dthree** [comment]
Yeah - I'm going to fix this with `vantage`, but I have to do more research on how that stuff works.

**Comment by Qix-** [comment]
Depending on how you have it now, CTRL+C sends SIGINT to the process. Pretty sure node has these abstracted across platforms, and you can [register a SIGINT handler](https://nodejs.org/api/process.html#process_signal_events) to handle the event gracefully.

**Comment by dthree** [comment]
Thanks! Will use that data.

**Comment by dthree** [comment]
Okay, updated `Vantage` to allow graceful sigint as well to allow a middlware function to be specified on sigint.

It terminates with one CONTROL + C, and for good measure says goodbye in one of 12 langauges :fire:
