### ISSUE TITLE
Improve search results

### ISSUE THREAD

**Issue by Qix-** [dthree/wat#6]
Alright so upon first use, specific things like `js array splice` work great - I love the format and it shows the two things I want the most - syntax, and an example.

I'm not sure if this is just a lack of documentation, or if it's a problem with the search itself, but here are some things that I feel should be pretty rudimentary.

- ES6 constructs (not just methods)
- Missing `Object.defineProperty`, etc.
- Order of keywords (i.e. `splice array`)
- ~~If mis-spellings were silently fixed on the fly, I'd love you forever~~ Nevermind, not sure where I thought they weren't.

<img width="250" alt="screen shot 2015-08-20 at 10 38 11 am" src="https://cloud.githubusercontent.com/assets/885648/9389297/93f4fbbc-4727-11e5-93f3-6983ebdb4f8d.png">

**Comment by dthree** [comment]
haha do you love me forever? jk

I use levenshtein distance to autocorrect depending on how close other matches are.

What you're running into is that I haven't added really any JS documentation yet. As soon as I finish the core functionality, I'll be going on a doc binge before releasing.

But try out `tab` twice - the autocompletion helps you out tremendously as to whats where.

**Comment by Qix-** [comment]
Aha, cool, that is nice.

**Comment by dthree** [comment]
Okay closing this. Let me know if there's any other improvement suggestions.
