### ISSUE TITLE
Wat exits with non-zero upon ^C

### ISSUE THREAD

**Issue by Qix-** [dthree/wat#7]
Upon exiting `wat` with CTRL+C, it returns non-zero (exit code 130 to be exact). It should probably exit with 0 :dancer:

**Comment by dthree** [comment]
Can do. Will be getting to these things a bit later on.

**Comment by Qix-** [comment]
No problem, just putting them on an official radar somewhere :)

**Comment by dthree** [comment]
Fixed on the latest release :rocket:
